### ISSUE TITLE
Suggestions for amendments

### ISSUE THREAD

**Issue by jennirpf** [raspberrypilearning/c3-wolfram-magic-8-ball#4]
Hi!

I have changed the spelling of non-committal within the code, but ensured that it is consistent throughout. I have also corrected some commas within the answers in the lists (e.g. "Yes, definitely"). If anything needs to be changed back, please let me know and I will undo the changes.

In step 4, I noticed an inconsistency: in the instructions, it says "using `Appearance->None`", but in the code it says "`Appearance -> None`" - do the spaces matter?

Thanks,
Jenni

**Comment by PhilipHarney** [comment]
The string changes are fine. The only things to worry about in string changes like that, as a general rule, are introducing special characters (`%` and `\` are often special characters) or closing the string by using the same kind of quote that was used to open it.

Step 4:
I don't know, but I've changed it to match the code as I know the code works — having tested it when I did my edits.
